name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Create a conda env quickly with micromamba
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: "latest"
          environment-name: ci
          create-args: >-
            python=3.10
            py-plumed
            pip
          cache-environment: true

      # Install SPARC package + run tests inside that env
      - name: Install SPARC and run tests
        shell: micromamba-shell {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install deepmd-kit[gpu,cu12]==2.2.10
          pip install -e .
          pytest -q

