name: JOSS PDF

on:
  workflow_dispatch: 
  push:
    paths:
      - paper/**
      - .github/workflows/joss-pdf.yml

jobs:
  build:
    name: Build draft PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-draft
          path: paper/paper.pdf

